// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcD4p4_Ep7RJ2d4G8m62lc-5IxUDoy754',
    appId: '1:155073571358:web:292385b816a0b878fb9c0f',
    messagingSenderId: '155073571358',
    projectId: 'taskflow-19f2e',
    authDomain: 'taskflow-19f2e.firebaseapp.com',
    storageBucket: 'taskflow-19f2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhwq1rsjUi-DDss1f1ub1n1wy4biAogZQ',
    appId: '1:155073571358:android:d787d5da71f4b8ccfb9c0f',
    messagingSenderId: '155073571358',
    projectId: 'taskflow-19f2e',
    storageBucket: 'taskflow-19f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7uJwSPw-xEDFgUGGsu9Kw9krGn8ROAA',
    appId: '1:155073571358:ios:ea5f49f48bb64723fb9c0f',
    messagingSenderId: '155073571358',
    projectId: 'taskflow-19f2e',
    storageBucket: 'taskflow-19f2e.firebasestorage.app',
    androidClientId: '155073571358-47q7eqrfrtoj505410uj4ounei2m7m4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu7uJwSPw-xEDFgUGGsu9Kw9krGn8ROAA',
    appId: '1:155073571358:ios:ea5f49f48bb64723fb9c0f',
    messagingSenderId: '155073571358',
    projectId: 'taskflow-19f2e',
    storageBucket: 'taskflow-19f2e.firebasestorage.app',
    androidClientId: '155073571358-47q7eqrfrtoj505410uj4ounei2m7m4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcD4p4_Ep7RJ2d4G8m62lc-5IxUDoy754',
    appId: '1:155073571358:web:dee0f42d1fac6d6cfb9c0f',
    messagingSenderId: '155073571358',
    projectId: 'taskflow-19f2e',
    authDomain: 'taskflow-19f2e.firebaseapp.com',
    storageBucket: 'taskflow-19f2e.firebasestorage.app',
  );
}
